apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "events.fullname" . }}
  labels:
    app: {{ template "events.name" . }}
    chart: {{ template "events.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "events.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "events.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/docker-entrypoint", "events"]
          env:
            - name: NODE_ENV
              value: {{ .Values.environment }}
          volumeMounts:
            - name: config
              mountPath: "/mnt/config"
              readOnly: true
          ports:
            - name: webhook
              containerPort: 3401
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 3401
            initialDelaySeconds: 60 # Events is super slow to start for some reason
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 3401
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

      volumes:
        - name: config
          secret:
            secretName: media-config
