apiVersion: v1
kind: Service
metadata:
  name: {{ template "events.fullname" . }}
  labels:
    app: {{ template "events.name" . }}
    chart: {{ template "events.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 3401
      protocol: TCP
      name: webhook
  selector:
    app: {{ template "events.name" . }}
    release: {{ .Release.Name }}
{{- with .Values.externalIps }}
  externalIps:
{{ toYaml . | indent 4 }}
{{- end }}
