apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "beholder.fullname" . }}
  labels:
    app: {{ template "beholder.name" . }}
    chart: {{ template "beholder.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "beholder.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "beholder.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: config
          secret:
            secretName: media-config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/usr/bin/docker-entrypoint", "beholder" ]
          env:
            - name: NODE_ENV
              value: {{ .Values.environment }}
          volumeMounts:
            - name: config
              mountPath: "/mnt/config"
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
