version: '3.3'
services:

  # Redis Instance
  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379 # Allow swapping services locally
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  ###########################################
  # Our Services
  converter:
    build: ./
    environment:
      MEDIA: 'http://twilight:8001'
      REDIS: 'redis://redis:6379'
    command: converter
    volumes:
      - ./config:/mnt/config
    configs:
      - source: config
        target: /mnt/config/config.yaml

  events:
    build: ./
    environment:
      REDIS: 'redis://redis:6379'
    command: events
    ports:
      - 3401:3401 # Webhook
    volumes:
      - ./config:/mnt/config
    configs:
      - source: config
        target: /mnt/config/config.yaml

  deploy:
    build: ./
    environment:
      REDIS: 'redis://redis:6379'
    command: deploy
    volumes:
      - ./config:/mnt/config
    configs:
      - source: config
        target: /mnt/config/config.yaml

  twilight:
    build: ./
    environment:
      REDIS: 'redis://redis:6379'
    command: twilight
    ports:
      - 8001:8001
    volumes:
      - ./config:/mnt/config
    configs:
      - source: config
        target: /mnt/config/config.yaml

# Only Docker Stack, fuck you Docker
configs:
  config:
    file: config/config.yaml
