version: '3'
services:

  # Redis Instance
  redis:
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  ###########################################
  # Our Services
  converter:
    build: ./
    environment:
      REDIS: 'redis://redis:6379'
    command: converter

  events:
    build: ./
    environment:
      REDIS: 'redis://redis:6379'
    command: events

  deploy:
    build: ./
    environment:
      REDIS: 'redis://redis:6379'
    command: deploy
