#cloud-config
package_update: true
users:
  - name: deploy
    groups:
      - sudo
      - docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - {{SSH_KEY}}
