#!/usr/bin/dumb-init /bin/bash
#
# (c) 2018 Jared Allard <jaredallard@outlook.com>
#

SERVICE=$1
CMD=$2

echo "Started: $(date)"
echo "opts: $@"

# Make sure the service exists.
if [[ -z "${SERVICE}" ]] || [[ ! -e "${SERVICE}" ]]; then
  echo "Service not found or not supplied"
  exit 1
fi

pushd "${SERVICE}" > /dev/null
  yarn

  echo "cmd: $(pwd)"
  echo -n "exec: "
  if [[ -z "$CMD" ]]; then
    echo "node index.js"
    node index.js
  else
    echo "${CMD}"
    "$CMD"
  fi

popd > /dev/null
