replicaCount: 1

image:
  repository: jaredallard/media-stack
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 500m
    memory: 500Mi

environment: debug

nodeSelector: {}

tolerations: []

affinity: {}
