replicaCount: 1

image:
  repository: jaredallard/media-stack
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 300m
    memory: 1Gi

environment: debug

nodeSelector: {}

tolerations: []

affinity: {}
