apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "emby.fullname" . }}
  labels:
    app: {{ template "emby.name" . }}
    chart: {{ template "emby.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "emby.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "emby.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: emby-media-pvc
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
           capabilities:
             add:
               - SYS_ADMIN
          volumeMounts:
            - name: media
              mountPath: "{{ .Values.storage.mountPath }}"
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
