apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-media
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nolock
    - nfsvers=4.1
    - loud
  nfs:
    server: nfs
    path: "/"
