# Production Config

# Redis configuration
redis:
  nodeSelector:
    triton.state: stable
  usePassword: false
  persistence: # don't persist jobs
    enabled: false

# Service configuration
deploy:
  environment: debug
  nodeSelector:
    triton.state: stable

events:
  replicaCount: 1
  environment: debug
  nodeSelector:
    triton.state: stable
  externalIps:
    - 138.68.241.148

beholder:
  environment: debug

media:
  twilight:
    environment: debug

  nodeSelector:
    triton.state: stable
    triton.role: storage # for when hostPath works
  externalIps:
    - 138.68.241.148

  storage:
    size: 800Gi
    hostPath: "/mnt/media-v1"
    mountPath: "/mnt/media-v1"

converter:
  environment: debug
  nodeSelector:
    triton.role: bigdata
