# Staging Config
global:
  endpoints:
    events: app.staging.tritonjs.com
    media:  media.staging.tritonjs.com
    deploy: deploy.staging.tritonjs.com

# Redis configuration
redis:
  usePassword: false
  persistence: # don't persist jobs
    enabled: false

# Service configuration
deploy:
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
  environment: debug

events:
  replicaCount: 1
  environment: debug

beholder:
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
  environment: debug

media:
  twilight:
    environment: debug
    resources:
      requests:
        cpu: 100m
        memory: 300Mi

  storage:
    size: 800Gi
    hostPath: "/mnt/media-v1"
    mountPath: "/mnt/media-v1"

converter:
  environment: debug
