

# Redis configuration
redis:
  nodeSelector:
    triton.state: stable
  usePassword: false
  persistence: # don't persist jobs
    enabled: false

# Service configuration
deploy:
  environment: production
  nodeSelector:
    triton.state: stable

events:
  replicaCount: 2
  environment: production
  nodeSelector:
    triton.state: stable
  externalIps: # Hardcode the prod instance IP
    - 159.65.75.17
    - 159.65.72.140

emby:
  nodeSelector:
    triton.state: stable
    triton.role: storage # for when hostPath works
  externalIps: # Hardcode the prod instance IP
    - 159.65.75.17

twilight:
  environment: production
  nodeSelector:
    triton.state: stable
  storage:
    hostPath: "/mnt/media-v1"
    mountPath: "/mnt/media-v1"

converter:
  environment: production
  nodeSelector:
    triton.role: bigdata
