replicaCount: 1

image:
  repository: jaredallard/media-stack
  tag: latest
  pullPolicy: Always

storage:
  size: 800Gi
  hostPath: "/mnt/media-v1"
  mountPath: "/mnt/media-v1"

environment: debug

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
