kind: PersistentVolume
apiVersion: v1
metadata:
  name: media
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.storage.hostPath }}"
