kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
