apiVersion: v1
kind: Service
metadata:
  name: emby
  labels:
    app: emby
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8096
      protocol: TCP
      name: http
  selector:
    app: media
    release: {{ .Release.Name }}
{{- with .Values.externalIps }}
  externalIps:
{{ toYaml . | indent 4 }}
{{- end }}
