apiVersion: v1
kind: Service
metadata:
  name: twilight
  labels:
    app: twilight
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: media
    release: {{ .Release.Name }}
